-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 13:57:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recipe_master
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recipe_master
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recipe_master` DEFAULT CHARACTER SET utf8 ;
USE `recipe_master` ;

-- -----------------------------------------------------
-- Table `recipe_master`.`types_of_dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe_master`.`types_of_dishes` (
  `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recipe_master`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe_master`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `biography` TEXT NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recipe_master`.`dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe_master`.`dishes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `prep_time` VARCHAR(45) NULL DEFAULT NULL,
  `portions` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `type_id` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dishes_users_idx` (`user_id` ASC),
  INDEX `fk_dishes_types_of_dishes_idx` (`type_id` ASC),
  CONSTRAINT `fk_dishes_types_of_dishes`
    FOREIGN KEY (`type_id`)
    REFERENCES `recipe_master`.`types_of_dishes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dishes_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `recipe_master`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recipe_master`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe_master`.`comments` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `dish_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users_idx` (`user_id` ASC),
  INDEX `fk_comments_dishes_idx` (`dish_id` ASC),
  CONSTRAINT `fk_comments_dishes`
    FOREIGN KEY (`dish_id`)
    REFERENCES `recipe_master`.`dishes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `recipe_master`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recipe_master`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe_master`.`ingredients` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `unit` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recipe_master`.`dishes_has_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe_master`.`dishes_has_ingredients` (
  `dish_id` INT(10) UNSIGNED NOT NULL,
  `ingredient_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `quantity` DECIMAL(5,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`dish_id`, `ingredient_id`),
  INDEX `fk_dishes_has_ingredients_ingredients_idx` (`ingredient_id` ASC),
  INDEX `fk_dishes_has_ingredients_dishes_idx` (`dish_id` ASC),
  CONSTRAINT `fk_dishes_has_ingredients_dishes`
    FOREIGN KEY (`dish_id`)
    REFERENCES `recipe_master`.`dishes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dishes_has_ingredients_ingredients`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `recipe_master`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recipe_master`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe_master`.`ratings` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `dish_id` INT(10) UNSIGNED NOT NULL,
  `value` DECIMAL(3,1) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `dish_id`),
  INDEX `fk_ratings_users_idx` (`user_id` ASC),
  INDEX `fk_ratings_dishes_idx` (`dish_id` ASC),
  CONSTRAINT `fk_ratings_dishes`
    FOREIGN KEY (`dish_id`)
    REFERENCES `recipe_master`.`dishes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratings_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `recipe_master`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
